add frontend & gateway CI

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -112,13 +112,21 @@ jobs:
         cd frontend/
         rm -rf node_modules
         npm install --legacy-peer-deps --force
-        ls node_modules/.bin/react-scripts || echo "React-scripts not found!"
+        ls node_modules/.bin || echo "Bin files not found!"
+        ls node_modules/react-scripts || echo "React-scripts not installed!"
+    - name: Create test environment
+      run: |
+        cd frontend/
+        echo "global.clearImmediate = global.setImmediate = (cb) => setTimeout(cb, 0);" > src/setupTests.js
+        echo 'module.exports = {' > jest.config.js
+        echo '  setupFilesAfterEnv: ["<rootDir>/src/setupTests.js"],' >> jest.config.js
+        echo '  setupFilesAfterEnv: ["<rootDir>/src/setupTests.js"],' >> jest.config.js
+        echo '};' >> jest.config.js
     - name: Test frontend
       # Запускаем тесты
       run: |
         cd frontend/
-        echo "global.clearImmediate = global.setImmediate = (cb) => setTimeout(cb, 0);" > temp-polyfill.js
-        NODE_OPTIONS="--require ./temp-polyfill.js" npm test -- --watchAll=false
+        NODE_OPTIONS="--require ./src/setupTests.js" npm test -- --watchAll=false --config=jest.config.js
   build_frontend_and_push_to_docker_hub:
     name: Push frontend Docker image to DockerHub
     runs-on: ubuntu-latest
